/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 whenever the process is up. No authentication.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 once the control plane is ready to accept traffic. No authentication.
         */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read whether first-administrator setup is still required */
        get: operations["getSetupStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomically create the first platform administrator */
        post: operations["setupAdministrator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Establish a session */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consume a one-time password reset token and revoke old sessions */
        post: operations["resetLocalPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List local users */
        get: operations["listUsers"];
        put?: never;
        /** Create a local user */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        /** Read a local user */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update display name, status, or global roles */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/users/{userId}/password-reset-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a short-lived one-time local password reset token */
        post: operations["issuePasswordResetToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the fleet overview */
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List visible servers */
        get: operations["listServers"];
        put?: never;
        /** Create a server */
        post: operations["createServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{serverId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        /** Read server details */
        get: operations["getServer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{serverId}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        /** Read the current actor's effective server permissions */
        get: operations["getEffectiveServerPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{serverId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        /** Read a server membership */
        get: operations["getServerMembership"];
        /** Grant or replace server-scoped permissions */
        put: operations["putServerMembership"];
        post?: never;
        /** Revoke server access immediately */
        delete: operations["deleteServerMembership"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{serverId}/power": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a power transition */
        post: operations["requestPower"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{serverId}/allocations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        /** List network allocations assigned to a server */
        get: operations["listServerAllocations"];
        put?: never;
        /** Assign a unique node endpoint and reconcile the server */
        post: operations["createServerAllocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{serverId}/allocations/{allocationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
                allocationId: components["parameters"]["AllocationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Release a non-primary allocation and reconcile the server */
        delete: operations["deleteServerAllocation"];
        options?: never;
        head?: never;
        /** Atomically promote an allocation to primary and reconcile the server */
        patch: operations["promoteServerAllocation"];
        trace?: never;
    };
    "/servers/{serverId}/startup": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        /** Read the resolved command and declared startup variables */
        get: operations["getServerStartup"];
        /** Validate startup variables and reconcile the server */
        put: operations["updateServerStartup"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{serverId}/console": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        /** Read a console snapshot */
        get: operations["getConsoleSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{serverId}/console/commands": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a console command */
        post: operations["sendConsoleCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{serverId}/files": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        /** List server files */
        get: operations["listFiles"];
        put?: never;
        post?: never;
        /** Delete a file or directory inside the server root */
        delete: operations["deleteServerFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{serverId}/files/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        /** Read a bounded regular file */
        get: operations["readServerFile"];
        /** Atomically create or replace a bounded regular file */
        put: operations["writeServerFile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{serverId}/files/directories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create one directory below an existing safe parent */
        post: operations["createServerDirectory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{serverId}/files/moves": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move or rename a file or directory */
        post: operations["moveServerFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{serverId}/backups": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        /** List server backups */
        get: operations["listBackups"];
        put?: never;
        /** Create a server backup */
        post: operations["createBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{serverId}/backups/{backupId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
                backupId: components["parameters"]["BackupId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a verified backup while the server is stopped */
        post: operations["restoreServerBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{serverId}/backups/{backupId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
                backupId: components["parameters"]["BackupId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a backup through an asynchronous operation */
        delete: operations["deleteServerBackup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{serverId}/backups/{backupId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
                backupId: components["parameters"]["BackupId"];
            };
            cookie?: never;
        };
        /**
         * 下载备份归档
         * @description Streams the verified backup archive as an attachment. Requires the servers.backups.read permission on the server.
         */
        get: operations["downloadServerBackup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered nodes */
        get: operations["listNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a node immediately
         * @description Revoked nodes are disconnected at the next heartbeat and cannot reconnect or receive work.
         */
        delete: operations["revokeNode"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent-enrollment-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a short-lived single-use agent enrollment token
         * @description The plaintext token is returned exactly once; only its digest is retained server-side.
         */
        post: operations["issueAgentEnrollmentToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List game definitions */
        get: operations["listGameDefinitions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List operations visible through current server read grants */
        get: operations["listOperations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/{operationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an operation */
        get: operations["getOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit events */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        Uuid: string;
        SetupStatusResponse: {
            data: {
                required: boolean;
                /** Format: date-time */
                bootstrapExpiresAt?: string;
            };
        };
        SetupAdminRequest: {
            bootstrapToken: string;
            /** Format: email */
            email: string;
            displayName: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        User: {
            id: components["schemas"]["Uuid"];
            /** Format: email */
            email: string;
            displayName: string;
            roles: string[];
            /** @enum {string} */
            status: "active" | "disabled";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UserResponse: {
            data: components["schemas"]["User"];
        };
        UserListResponse: {
            data: components["schemas"]["User"][];
        };
        CreateUserRequest: {
            /** Format: email */
            email: string;
            displayName: string;
            password: string;
            roles: ("platform_admin" | "server_owner")[];
        };
        UpdateUserRequest: {
            displayName?: string;
            /** @enum {string} */
            status?: "active" | "disabled";
            roles?: ("platform_admin" | "server_owner")[];
        };
        PasswordResetRequest: {
            token: string;
            password: string;
        };
        PasswordResetToken: {
            /** @description Plaintext is returned exactly once; persistence retains only a SHA-256 digest. */
            token: string;
            /** Format: date-time */
            expiresAt: string;
        };
        PasswordResetTokenResponse: {
            data: components["schemas"]["PasswordResetToken"];
        };
        /** @enum {string} */
        ServerPermission: "servers.read" | "servers.power" | "servers.console" | "servers.files.read" | "servers.files.write" | "servers.backups.read" | "servers.backups.create" | "servers.backups.restore" | "servers.backups.delete" | "servers.network.read" | "servers.network.write" | "servers.startup.read" | "servers.startup.write";
        PutServerMembershipRequest: {
            permissions: components["schemas"]["ServerPermission"][];
        };
        ServerMembership: {
            serverId: components["schemas"]["Uuid"];
            userId: components["schemas"]["Uuid"];
            permissions: components["schemas"]["ServerPermission"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ServerMembershipResponse: {
            data: components["schemas"]["ServerMembership"];
        };
        ServerPermissions: {
            serverId: components["schemas"]["Uuid"];
            permissions: components["schemas"]["ServerPermission"][];
        };
        ServerPermissionsResponse: {
            data: components["schemas"]["ServerPermissions"];
        };
        SessionResponse: {
            data: {
                user: components["schemas"]["User"];
                csrfToken: string;
                /** @enum {string} */
                environment: "development" | "production";
            };
        };
        ResourceMetrics: {
            cpuPercent: number;
            memoryBytes: number;
            memoryLimitBytes: number;
            diskBytes: number;
            diskLimitBytes: number;
            networkRxBytes?: number;
            networkTxBytes?: number;
            playersOnline?: number;
            playersMax?: number;
        };
        MetricPoint: {
            /** Format: date-time */
            timestamp: string;
            cpuPercent: number;
            memoryBytes: number;
        };
        Server: {
            id: components["schemas"]["Uuid"];
            name: string;
            description: string;
            gameId: string;
            /** @description Immutable sha256 identity of the published Bundle; it is not the game release version or a component image digest. */
            gameBundleDigest: string;
            /** @description SemVer of the immutable GameDefinition selected at creation time. */
            gameDefinitionVersion: string;
            gameName: string;
            /** @description Opaque upstream game release identifier resolved from spec.release.version. */
            gameVersion: string;
            nodeId: components["schemas"]["Uuid"];
            nodeName: string;
            /** @enum {string} */
            lifecycleState: "provisioning" | "ready" | "deleting" | "deleted";
            /** @enum {string} */
            desiredPower: "running" | "stopped";
            /** @enum {string} */
            observedPower: "unknown" | "stopped" | "starting" | "running" | "stopping";
            /** @enum {string} */
            nodeCondition: "available" | "offline" | "maintenance";
            /** @enum {string} */
            healthCondition: "unknown" | "healthy" | "unhealthy";
            generation: number;
            observedGeneration: number;
            /** Format: date-time */
            observedAt: string;
            allocation: string;
            ownerName: string;
            metrics: components["schemas"]["ResourceMetrics"];
            metricHistory: components["schemas"]["MetricPoint"][];
            /** Format: date-time */
            updatedAt: string;
        };
        ServerListResponse: {
            data: components["schemas"]["Server"][];
            page: {
                nextCursor: string | null;
            };
        };
        CreateServerRequest: {
            name: string;
            gameDefinitionId: string;
            /** @description Immutable sha256 identity of the selected published Bundle; the server resolves its definition and upstream game versions from the catalog record. */
            gameBundleDigest: string;
            nodeId: components["schemas"]["Uuid"];
            memoryMb: number;
            diskGb: number;
        };
        Allocation: {
            id: components["schemas"]["Uuid"];
            serverId: components["schemas"]["Uuid"];
            nodeId: components["schemas"]["Uuid"];
            /** @description Canonical IPv4 or IPv6 bind address. Unspecified wildcard addresses (0.0.0.0 and ::) are rejected. */
            bindIp: string;
            port: number;
            /** @enum {string} */
            protocol: "tcp" | "udp";
            /** @description Exactly one allocation per server is primary. */
            primary: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateAllocationRequest: {
            bindIp: string;
            port: number;
            /** @enum {string} */
            protocol: "tcp" | "udp";
            primary: boolean;
        };
        PromoteAllocationRequest: {
            /** @constant */
            primary: true;
        };
        StartupCommand: {
            executable: string;
            args: string[];
        };
        /** @description A Startup value. Integer values use the JavaScript safe integer domain. */
        StartupScalar: string | number | boolean;
        /** @description Secret variables expose only declaration metadata and hasValue; value, default, constValue, and enumValues are omitted. */
        StartupVariable: {
            key: string;
            /**
             * @description Integer variables use the JavaScript safe integer domain (-9007199254740991 through 9007199254740991).
             * @enum {string}
             */
            type: "string" | "integer" | "boolean";
            secret: boolean;
            required: boolean;
            /** @description Declared default for a non-secret variable. */
            default?: components["schemas"]["StartupScalar"];
            /** @description Configured non-secret value. This member is never returned for a secret variable. */
            value?: components["schemas"]["StartupScalar"];
            hasValue: boolean;
            minimum?: number;
            maximum?: number;
            minLength?: number;
            maxLength?: number;
            /** @description Declared candidates for a non-secret string variable. */
            enumValues?: string[];
            /** @description Required constant value for a non-secret variable when declared by the game definition. */
            constValue?: components["schemas"]["StartupScalar"];
        } & unknown;
        Startup: {
            serverId: components["schemas"]["Uuid"];
            generation: number;
            command: components["schemas"]["StartupCommand"];
            variables: components["schemas"]["StartupVariable"][];
        };
        UpdateStartupRequest: {
            /** @description Declared variable updates. Null clears an optional value, including a secret. Integer values are limited to the JavaScript safe integer domain. */
            variables: {
                [key: string]: components["schemas"]["StartupScalar"] | null;
            };
        };
        OperationError: {
            code: string;
            message: string;
            retryable: boolean;
        };
        Operation: {
            id: components["schemas"]["Uuid"];
            serverId: components["schemas"]["Uuid"];
            nodeId: components["schemas"]["Uuid"];
            /** @enum {string} */
            type: "provision" | "start" | "stop" | "restart" | "kill" | "backup" | "restore" | "backup-delete" | "delete" | "reconcile";
            /** @enum {string} */
            status: "queued" | "leased" | "running" | "succeeded" | "failed";
            progress: number;
            generation: number;
            attempt: number;
            maxAttempts: number;
            leaseOwner: string | null;
            /** Format: date-time */
            leaseExpiresAt: string | null;
            checkpoint: string;
            error: components["schemas"]["OperationError"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OperationResponse: {
            data: components["schemas"]["Operation"];
        };
        OperationListResponse: {
            data: components["schemas"]["Operation"][];
            page: {
                nextCursor: string | null;
            };
        };
        Node: {
            id: components["schemas"]["Uuid"];
            name: string;
            /** @enum {string} */
            condition: "available" | "offline" | "maintenance";
            version: string;
            region: string;
            address: string;
            /** Format: date-time */
            lastHeartbeatAt: string;
            cpuCores: number;
            memoryBytes: number;
            diskBytes: number;
            allocatedMemoryBytes: number;
            allocatedDiskBytes: number;
            runningServers: number;
            totalServers: number;
            capabilities: string[];
        };
        GameDefinition: {
            id: string;
            /** @description Immutable sha256 identity of the published Bundle; it is not the upstream game release version or a component image digest. */
            bundleDigest: string;
            name: string;
            summary: string;
            /** @description SemVer of this GameDefinition, not the upstream game release. */
            version: string;
            /** @description Opaque upstream game release identifier resolved from spec.release.version. */
            gameVersion: string;
            /** @enum {string} */
            status: "approved" | "pending" | "rejected";
            capabilities: string[];
            platforms: string[];
            servers: number;
            icon: string;
            defaultMemoryMb: number;
            defaultDiskGb: number;
            /** @description True only when cryptographic signature material is present; a digest or signer label alone is not a signature. */
            signed: boolean;
            /** @description True only after the signature and authenticated publisher identity have been verified by the control plane. */
            verified: boolean;
            /** @description True only when the current Agent contract can consume and execute an immutable runtime target for this exact Bundle. */
            runnable: boolean;
            /** @description Overall support claim; requires an approved, verified, and runnable Bundle. */
            supported: boolean;
            /** @enum {string} */
            trustLevel: "L0_LOCAL" | "L1_COMMUNITY" | "L2_GUGU_VERIFIED" | "L3_VENDOR";
            /** @description Provenance of the catalog metadata, not proof of publisher identity. */
            source: string;
            supportReasons: string[];
        };
        ConsoleLine: {
            sequence: number;
            /** Format: date-time */
            timestamp: string;
            /** @enum {string} */
            stream: "system" | "stdout" | "stderr" | "command";
            message: string;
        };
        FileEntry: {
            name: string;
            path: string;
            /** @enum {string} */
            kind: "file" | "directory";
            sizeBytes: number;
            /** Format: date-time */
            modifiedAt: string;
        };
        FileContent: {
            path: string;
            content: string;
            /** @enum {string} */
            encoding: "utf-8" | "base64";
            sizeBytes: number;
            /** Format: date-time */
            modifiedAt: string;
        };
        Backup: {
            id: components["schemas"]["Uuid"];
            name: string;
            /** @enum {string} */
            status: "creating" | "ready" | "failed" | "restoring" | "deleting";
            sizeBytes?: number | null;
            checksum?: string | null;
            manifestDigest?: string | null;
            storageLocation?: string | null;
            /** Format: date-time */
            retentionUntil?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt?: string | null;
            /** @description Stable machine-readable failure code for the latest failed transition. */
            failureCode?: string | null;
            /** @description Safe operator-facing explanation for the latest failed transition. */
            failureMessage?: string | null;
            /**
             * Format: date-time
             * @description Soft-delete timestamp retained for recovery and garbage collection.
             */
            deletedAt?: string | null;
        };
        AuditEvent: {
            id: components["schemas"]["Uuid"];
            actorName: string;
            action: string;
            targetType: string;
            targetName: string;
            /** @enum {string} */
            result: "accepted" | "success" | "failure";
            /** Format: uuid */
            operationId: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        Overview: {
            /** @enum {string} */
            environment: "development" | "production";
            serverCount: number;
            runningServerCount: number;
            onlineNodeCount: number;
            totalNodeCount: number;
            queuedOperationCount: number;
            cpuPercent: number;
            memoryUsedBytes: number;
            memoryTotalBytes: number;
            recentActivity: components["schemas"]["AuditEvent"][];
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                retryable: boolean;
                /** Format: uuid */
                operationId?: string | null;
                traceId: components["schemas"]["Uuid"];
                details: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: {
        /** @description Structured API error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Login attempts are temporarily blocked for an account or source IP */
        RateLimited: {
            headers: {
                "Retry-After": number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        ServerId: components["schemas"]["Uuid"];
        UserId: components["schemas"]["Uuid"];
        NodeId: components["schemas"]["Uuid"];
        BackupId: components["schemas"]["Uuid"];
        AllocationId: components["schemas"]["Uuid"];
        Cursor: string;
        Limit: number;
        IdempotencyKey: string;
        /** @description Numeric server generation read before submitting the mutation. */
        IfMatchGeneration: number;
        CsrfToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready to accept traffic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ready";
                        /** @description Storage adapter in use, e.g. development-memory. */
                        adapter: string;
                    };
                };
            };
            /** @description A required dependency, canonical migration, or encryption key is not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "not_ready";
                        /** @description Configured runtime adapter. */
                        adapter: string;
                    };
                };
            };
        };
    };
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setup state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusResponse"];
                };
            };
        };
    };
    setupAdministrator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupAdminRequest"];
            };
        };
        responses: {
            /** @description First administrator created and setup permanently closed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
            415: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session established */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["Error"];
            415: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    resetLocalPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Password replaced and all prior sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            415: components["responses"]["Error"];
            422: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Local user created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            415: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Updated local user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            415: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    issuePasswordResetToken: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One-time plaintext token; only its digest is retained */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetTokenResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fleet overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Overview"];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    listServers: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servers visible to the current actor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerListResponse"];
                };
            };
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    createServer: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServerRequest"];
            };
        };
        responses: {
            /** @description Provision operation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            415: components["responses"]["Error"];
            422: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Server"];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getEffectiveServerPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Effective permissions for the current actor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerPermissionsResponse"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getServerMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server membership */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerMembershipResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    putServerMembership: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                serverId: components["parameters"]["ServerId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutServerMembershipRequest"];
            };
        };
        responses: {
            /** @description Server membership granted or replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerMembershipResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            415: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    deleteServerMembership: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                serverId: components["parameters"]["ServerId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server membership revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    requestPower: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    action: "start" | "stop" | "restart" | "kill";
                };
            };
        };
        responses: {
            /** @description Power operation accepted or reused */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            415: components["responses"]["Error"];
            422: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listServerAllocations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server network allocations with exactly one primary allocation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Allocation"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    createServerAllocation: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Numeric server generation read before submitting the mutation. */
                "If-Match": components["parameters"]["IfMatchGeneration"];
            };
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAllocationRequest"];
            };
        };
        responses: {
            /** @description Allocation reconciliation accepted or idempotently reused */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            412: components["responses"]["Error"];
            415: components["responses"]["Error"];
            422: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    deleteServerAllocation: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Numeric server generation read before submitting the mutation. */
                "If-Match": components["parameters"]["IfMatchGeneration"];
            };
            path: {
                serverId: components["parameters"]["ServerId"];
                allocationId: components["parameters"]["AllocationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Allocation release reconciliation accepted or idempotently reused */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            412: components["responses"]["Error"];
            422: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    promoteServerAllocation: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Numeric server generation read before submitting the mutation. */
                "If-Match": components["parameters"]["IfMatchGeneration"];
            };
            path: {
                serverId: components["parameters"]["ServerId"];
                allocationId: components["parameters"]["AllocationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoteAllocationRequest"];
            };
        };
        responses: {
            /** @description Primary-allocation reconciliation accepted or idempotently reused */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            412: components["responses"]["Error"];
            415: components["responses"]["Error"];
            422: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getServerStartup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Startup configuration; secret variables expose only hasValue state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Startup"];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    updateServerStartup: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Numeric server generation read before submitting the mutation. */
                "If-Match": components["parameters"]["IfMatchGeneration"];
            };
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStartupRequest"];
            };
        };
        responses: {
            /** @description Startup reconciliation accepted or idempotently reused */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            412: components["responses"]["Error"];
            415: components["responses"]["Error"];
            422: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getConsoleSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Development console snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ConsoleLine"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    sendConsoleCommand: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    command: string;
                };
            };
        };
        responses: {
            /** @description Command accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            415: components["responses"]["Error"];
            422: components["responses"]["Error"];
            502: components["responses"]["Error"];
            503: components["responses"]["Error"];
            504: components["responses"]["Error"];
        };
    };
    listFiles: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FileEntry"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    deleteServerFile: {
        parameters: {
            query: {
                path: string;
                recursive?: boolean;
            };
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entry deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    readServerFile: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content encoded as UTF-8 or unpadded base64 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FileContent"];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    writeServerFile: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    path: string;
                    content: string;
                    /**
                     * @default utf-8
                     * @enum {string}
                     */
                    encoding?: "utf-8" | "base64";
                };
            };
        };
        responses: {
            /** @description File written atomically */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            415: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    createServerDirectory: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    path: string;
                };
            };
        };
        responses: {
            /** @description Directory created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            415: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    moveServerFile: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    source: string;
                    destination: string;
                    replace: boolean;
                };
            };
        };
        responses: {
            /** @description Entry moved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            415: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listBackups: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Backup"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    createBackup: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                serverId: components["parameters"]["ServerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backup operation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    restoreServerBackup: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                serverId: components["parameters"]["ServerId"];
                backupId: components["parameters"]["BackupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restore operation accepted and exclusive restore lock acquired */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    deleteServerBackup: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                serverId: components["parameters"]["ServerId"];
                backupId: components["parameters"]["BackupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backup deletion operation accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    downloadServerBackup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: components["parameters"]["ServerId"];
                backupId: components["parameters"]["BackupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 备份归档二进制流 */
            200: {
                headers: {
                    /** @description attachment; filename="<backupId>.tar.gz" */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/gzip": string;
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listNodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nodes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Node"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    revokeNode: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    issueAgentEnrollmentToken: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    nodeNameHint?: string;
                    ttlSeconds?: number;
                };
            };
        };
        responses: {
            /** @description One-time plaintext enrollment token */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            token: string;
                            /** Format: date-time */
                            expiresAt: string;
                        };
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listGameDefinitions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approved game bundles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["GameDefinition"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listOperations: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operations ordered by immutable creation time and ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationListResponse"];
                };
            };
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operationId: components["schemas"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Append-only audit events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuditEvent"][];
                    };
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
}
