// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: gugumanager/agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentGatewayService_Connect_FullMethodName       = "/gugumanager.agent.v1.AgentGatewayService/Connect"
	AgentGatewayService_Enroll_FullMethodName        = "/gugumanager.agent.v1.AgentGatewayService/Enroll"
	AgentGatewayService_ResolveSecret_FullMethodName = "/gugumanager.agent.v1.AgentGatewayService/ResolveSecret"
)

// AgentGatewayServiceClient is the client API for AgentGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentGatewayServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectRequest, ConnectResponse], error)
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	ResolveSecret(ctx context.Context, in *ResolveSecretRequest, opts ...grpc.CallOption) (*ResolveSecretResponse, error)
}

type agentGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentGatewayServiceClient(cc grpc.ClientConnInterface) AgentGatewayServiceClient {
	return &agentGatewayServiceClient{cc}
}

func (c *agentGatewayServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectRequest, ConnectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentGatewayService_ServiceDesc.Streams[0], AgentGatewayService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnectRequest, ConnectResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGatewayService_ConnectClient = grpc.BidiStreamingClient[ConnectRequest, ConnectResponse]

func (c *agentGatewayServiceClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, AgentGatewayService_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentGatewayServiceClient) ResolveSecret(ctx context.Context, in *ResolveSecretRequest, opts ...grpc.CallOption) (*ResolveSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveSecretResponse)
	err := c.cc.Invoke(ctx, AgentGatewayService_ResolveSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentGatewayServiceServer is the server API for AgentGatewayService service.
// All implementations must embed UnimplementedAgentGatewayServiceServer
// for forward compatibility.
type AgentGatewayServiceServer interface {
	Connect(grpc.BidiStreamingServer[ConnectRequest, ConnectResponse]) error
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	ResolveSecret(context.Context, *ResolveSecretRequest) (*ResolveSecretResponse, error)
	mustEmbedUnimplementedAgentGatewayServiceServer()
}

// UnimplementedAgentGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentGatewayServiceServer struct{}

func (UnimplementedAgentGatewayServiceServer) Connect(grpc.BidiStreamingServer[ConnectRequest, ConnectResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentGatewayServiceServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedAgentGatewayServiceServer) ResolveSecret(context.Context, *ResolveSecretRequest) (*ResolveSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveSecret not implemented")
}
func (UnimplementedAgentGatewayServiceServer) mustEmbedUnimplementedAgentGatewayServiceServer() {}
func (UnimplementedAgentGatewayServiceServer) testEmbeddedByValue()                             {}

// UnsafeAgentGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentGatewayServiceServer will
// result in compilation errors.
type UnsafeAgentGatewayServiceServer interface {
	mustEmbedUnimplementedAgentGatewayServiceServer()
}

func RegisterAgentGatewayServiceServer(s grpc.ServiceRegistrar, srv AgentGatewayServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentGatewayService_ServiceDesc, srv)
}

func _AgentGatewayService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentGatewayServiceServer).Connect(&grpc.GenericServerStream[ConnectRequest, ConnectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGatewayService_ConnectServer = grpc.BidiStreamingServer[ConnectRequest, ConnectResponse]

func _AgentGatewayService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGatewayService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServiceServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentGatewayService_ResolveSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServiceServer).ResolveSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGatewayService_ResolveSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServiceServer).ResolveSecret(ctx, req.(*ResolveSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentGatewayService_ServiceDesc is the grpc.ServiceDesc for AgentGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gugumanager.agent.v1.AgentGatewayService",
	HandlerType: (*AgentGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _AgentGatewayService_Enroll_Handler,
		},
		{
			MethodName: "ResolveSecret",
			Handler:    _AgentGatewayService_ResolveSecret_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentGatewayService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gugumanager/agent/v1/agent.proto",
}
