// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gugumanager/extension/runner/v1/runner.proto

package runnerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Request_Hello
	//	*Request_Invoke
	//	*Request_Cancel
	Payload       isRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_gugumanager_extension_runner_v1_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_gugumanager_extension_runner_v1_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_gugumanager_extension_runner_v1_runner_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Request) GetPayload() isRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*Request_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Request) GetInvoke() *Invoke {
	if x != nil {
		if x, ok := x.Payload.(*Request_Invoke); ok {
			return x.Invoke
		}
	}
	return nil
}

func (x *Request) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Payload.(*Request_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isRequest_Payload interface {
	isRequest_Payload()
}

type Request_Hello struct {
	Hello *Hello `protobuf:"bytes,2,opt,name=hello,proto3,oneof"`
}

type Request_Invoke struct {
	Invoke *Invoke `protobuf:"bytes,3,opt,name=invoke,proto3,oneof"`
}

type Request_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

func (*Request_Hello) isRequest_Payload() {}

func (*Request_Invoke) isRequest_Payload() {}

func (*Request_Cancel) isRequest_Payload() {}

type Response struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Response_Hello
	//	*Response_Progress
	//	*Response_Result
	Payload       isResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_gugumanager_extension_runner_v1_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_gugumanager_extension_runner_v1_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_gugumanager_extension_runner_v1_runner_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Response) GetPayload() isResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Response) GetHello() *HelloAck {
	if x != nil {
		if x, ok := x.Payload.(*Response_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Response) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Payload.(*Response_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *Response) GetResult() *Result {
	if x != nil {
		if x, ok := x.Payload.(*Response_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isResponse_Payload interface {
	isResponse_Payload()
}

type Response_Hello struct {
	Hello *HelloAck `protobuf:"bytes,2,opt,name=hello,proto3,oneof"`
}

type Response_Progress struct {
	Progress *Progress `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

type Response_Result struct {
	Result *Result `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

func (*Response_Hello) isResponse_Payload() {}

func (*Response_Progress) isResponse_Payload() {}

func (*Response_Result) isResponse_Payload() {}

type Hello struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersions []uint32               `protobuf:"varint,1,rep,packed,name=protocol_versions,json=protocolVersions,proto3" json:"protocol_versions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_gugumanager_extension_runner_v1_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_gugumanager_extension_runner_v1_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_gugumanager_extension_runner_v1_runner_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetProtocolVersions() []uint32 {
	if x != nil {
		return x.ProtocolVersions
	}
	return nil
}

type HelloAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RunnerVersion   string                 `protobuf:"bytes,2,opt,name=runner_version,json=runnerVersion,proto3" json:"runner_version,omitempty"`
	Capabilities    []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_gugumanager_extension_runner_v1_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_gugumanager_extension_runner_v1_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_gugumanager_extension_runner_v1_runner_proto_rawDescGZIP(), []int{3}
}

func (x *HelloAck) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HelloAck) GetRunnerVersion() string {
	if x != nil {
		return x.RunnerVersion
	}
	return ""
}

func (x *HelloAck) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Invoke struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OperationId     string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ServerId        string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	BundleDigest    string                 `protobuf:"bytes,3,opt,name=bundle_digest,json=bundleDigest,proto3" json:"bundle_digest,omitempty"`
	ExtensionDigest string                 `protobuf:"bytes,4,opt,name=extension_digest,json=extensionDigest,proto3" json:"extension_digest,omitempty"`
	Component       []byte                 `protobuf:"bytes,5,opt,name=component,proto3" json:"component,omitempty"`
	Input           []byte                 `protobuf:"bytes,6,opt,name=input,proto3" json:"input,omitempty"`
	ServerRoot      string                 `protobuf:"bytes,7,opt,name=server_root,json=serverRoot,proto3" json:"server_root,omitempty"`
	Permissions     []string               `protobuf:"bytes,8,rep,name=permissions,proto3" json:"permissions,omitempty"`
	HttpsAllowlist  []string               `protobuf:"bytes,9,rep,name=https_allowlist,json=httpsAllowlist,proto3" json:"https_allowlist,omitempty"`
	SecretBindings  map[string][]byte      `protobuf:"bytes,10,rep,name=secret_bindings,json=secretBindings,proto3" json:"secret_bindings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Fuel            uint64                 `protobuf:"varint,11,opt,name=fuel,proto3" json:"fuel,omitempty"`
	MemoryBytes     uint64                 `protobuf:"varint,12,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	TimeoutMs       uint32                 `protobuf:"varint,13,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	MaxOutputBytes  uint64                 `protobuf:"varint,14,opt,name=max_output_bytes,json=maxOutputBytes,proto3" json:"max_output_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Invoke) Reset() {
	*x = Invoke{}
	mi := &file_gugumanager_extension_runner_v1_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoke) ProtoMessage() {}

func (x *Invoke) ProtoReflect() protoreflect.Message {
	mi := &file_gugumanager_extension_runner_v1_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoke.ProtoReflect.Descriptor instead.
func (*Invoke) Descriptor() ([]byte, []int) {
	return file_gugumanager_extension_runner_v1_runner_proto_rawDescGZIP(), []int{4}
}

func (x *Invoke) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *Invoke) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Invoke) GetBundleDigest() string {
	if x != nil {
		return x.BundleDigest
	}
	return ""
}

func (x *Invoke) GetExtensionDigest() string {
	if x != nil {
		return x.ExtensionDigest
	}
	return ""
}

func (x *Invoke) GetComponent() []byte {
	if x != nil {
		return x.Component
	}
	return nil
}

func (x *Invoke) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Invoke) GetServerRoot() string {
	if x != nil {
		return x.ServerRoot
	}
	return ""
}

func (x *Invoke) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Invoke) GetHttpsAllowlist() []string {
	if x != nil {
		return x.HttpsAllowlist
	}
	return nil
}

func (x *Invoke) GetSecretBindings() map[string][]byte {
	if x != nil {
		return x.SecretBindings
	}
	return nil
}

func (x *Invoke) GetFuel() uint64 {
	if x != nil {
		return x.Fuel
	}
	return 0
}

func (x *Invoke) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *Invoke) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *Invoke) GetMaxOutputBytes() uint64 {
	if x != nil {
		return x.MaxOutputBytes
	}
	return 0
}

type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_gugumanager_extension_runner_v1_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_gugumanager_extension_runner_v1_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_gugumanager_extension_runner_v1_runner_proto_rawDescGZIP(), []int{5}
}

func (x *Cancel) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percent       uint32                 `protobuf:"varint,1,opt,name=percent,proto3" json:"percent,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_gugumanager_extension_runner_v1_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_gugumanager_extension_runner_v1_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_gugumanager_extension_runner_v1_runner_proto_rawDescGZIP(), []int{6}
}

func (x *Progress) GetPercent() uint32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *Progress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeeded     bool                   `protobuf:"varint,1,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Output        []byte                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_gugumanager_extension_runner_v1_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_gugumanager_extension_runner_v1_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_gugumanager_extension_runner_v1_runner_proto_rawDescGZIP(), []int{7}
}

func (x *Result) GetSucceeded() bool {
	if x != nil {
		return x.Succeeded
	}
	return false
}

func (x *Result) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Result) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Result) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_gugumanager_extension_runner_v1_runner_proto protoreflect.FileDescriptor

const file_gugumanager_extension_runner_v1_runner_proto_rawDesc = "" +
	"\n" +
	",gugumanager/extension/runner/v1/runner.proto\x12\x1fgugumanager.extension.runner.v1\"\xf9\x01\n" +
	"\aRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12>\n" +
	"\x05hello\x18\x02 \x01(\v2&.gugumanager.extension.runner.v1.HelloH\x00R\x05hello\x12A\n" +
	"\x06invoke\x18\x03 \x01(\v2'.gugumanager.extension.runner.v1.InvokeH\x00R\x06invoke\x12A\n" +
	"\x06cancel\x18\x04 \x01(\v2'.gugumanager.extension.runner.v1.CancelH\x00R\x06cancelB\t\n" +
	"\apayload\"\x83\x02\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12A\n" +
	"\x05hello\x18\x02 \x01(\v2).gugumanager.extension.runner.v1.HelloAckH\x00R\x05hello\x12G\n" +
	"\bprogress\x18\x03 \x01(\v2).gugumanager.extension.runner.v1.ProgressH\x00R\bprogress\x12A\n" +
	"\x06result\x18\x04 \x01(\v2'.gugumanager.extension.runner.v1.ResultH\x00R\x06resultB\t\n" +
	"\apayload\"4\n" +
	"\x05Hello\x12+\n" +
	"\x11protocol_versions\x18\x01 \x03(\rR\x10protocolVersions\"\x80\x01\n" +
	"\bHelloAck\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12%\n" +
	"\x0erunner_version\x18\x02 \x01(\tR\rrunnerVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\xe1\x04\n" +
	"\x06Invoke\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12#\n" +
	"\rbundle_digest\x18\x03 \x01(\tR\fbundleDigest\x12)\n" +
	"\x10extension_digest\x18\x04 \x01(\tR\x0fextensionDigest\x12\x1c\n" +
	"\tcomponent\x18\x05 \x01(\fR\tcomponent\x12\x14\n" +
	"\x05input\x18\x06 \x01(\fR\x05input\x12\x1f\n" +
	"\vserver_root\x18\a \x01(\tR\n" +
	"serverRoot\x12 \n" +
	"\vpermissions\x18\b \x03(\tR\vpermissions\x12'\n" +
	"\x0fhttps_allowlist\x18\t \x03(\tR\x0ehttpsAllowlist\x12d\n" +
	"\x0fsecret_bindings\x18\n" +
	" \x03(\v2;.gugumanager.extension.runner.v1.Invoke.SecretBindingsEntryR\x0esecretBindings\x12\x12\n" +
	"\x04fuel\x18\v \x01(\x04R\x04fuel\x12!\n" +
	"\fmemory_bytes\x18\f \x01(\x04R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\r \x01(\rR\ttimeoutMs\x12(\n" +
	"\x10max_output_bytes\x18\x0e \x01(\x04R\x0emaxOutputBytes\x1aA\n" +
	"\x13SecretBindingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"+\n" +
	"\x06Cancel\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\">\n" +
	"\bProgress\x12\x18\n" +
	"\apercent\x18\x01 \x01(\rR\apercent\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"u\n" +
	"\x06Result\x12\x1c\n" +
	"\tsucceeded\x18\x01 \x01(\bR\tsucceeded\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x16\n" +
	"\x06output\x18\x03 \x01(\fR\x06output\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detailBWZUgithub.com/gugumanager/gugumanager/api/proto/gugumanager/extension/runner/v1;runnerv1b\x06proto3"

var (
	file_gugumanager_extension_runner_v1_runner_proto_rawDescOnce sync.Once
	file_gugumanager_extension_runner_v1_runner_proto_rawDescData []byte
)

func file_gugumanager_extension_runner_v1_runner_proto_rawDescGZIP() []byte {
	file_gugumanager_extension_runner_v1_runner_proto_rawDescOnce.Do(func() {
		file_gugumanager_extension_runner_v1_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gugumanager_extension_runner_v1_runner_proto_rawDesc), len(file_gugumanager_extension_runner_v1_runner_proto_rawDesc)))
	})
	return file_gugumanager_extension_runner_v1_runner_proto_rawDescData
}

var file_gugumanager_extension_runner_v1_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gugumanager_extension_runner_v1_runner_proto_goTypes = []any{
	(*Request)(nil),  // 0: gugumanager.extension.runner.v1.Request
	(*Response)(nil), // 1: gugumanager.extension.runner.v1.Response
	(*Hello)(nil),    // 2: gugumanager.extension.runner.v1.Hello
	(*HelloAck)(nil), // 3: gugumanager.extension.runner.v1.HelloAck
	(*Invoke)(nil),   // 4: gugumanager.extension.runner.v1.Invoke
	(*Cancel)(nil),   // 5: gugumanager.extension.runner.v1.Cancel
	(*Progress)(nil), // 6: gugumanager.extension.runner.v1.Progress
	(*Result)(nil),   // 7: gugumanager.extension.runner.v1.Result
	nil,              // 8: gugumanager.extension.runner.v1.Invoke.SecretBindingsEntry
}
var file_gugumanager_extension_runner_v1_runner_proto_depIdxs = []int32{
	2, // 0: gugumanager.extension.runner.v1.Request.hello:type_name -> gugumanager.extension.runner.v1.Hello
	4, // 1: gugumanager.extension.runner.v1.Request.invoke:type_name -> gugumanager.extension.runner.v1.Invoke
	5, // 2: gugumanager.extension.runner.v1.Request.cancel:type_name -> gugumanager.extension.runner.v1.Cancel
	3, // 3: gugumanager.extension.runner.v1.Response.hello:type_name -> gugumanager.extension.runner.v1.HelloAck
	6, // 4: gugumanager.extension.runner.v1.Response.progress:type_name -> gugumanager.extension.runner.v1.Progress
	7, // 5: gugumanager.extension.runner.v1.Response.result:type_name -> gugumanager.extension.runner.v1.Result
	8, // 6: gugumanager.extension.runner.v1.Invoke.secret_bindings:type_name -> gugumanager.extension.runner.v1.Invoke.SecretBindingsEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_gugumanager_extension_runner_v1_runner_proto_init() }
func file_gugumanager_extension_runner_v1_runner_proto_init() {
	if File_gugumanager_extension_runner_v1_runner_proto != nil {
		return
	}
	file_gugumanager_extension_runner_v1_runner_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_Hello)(nil),
		(*Request_Invoke)(nil),
		(*Request_Cancel)(nil),
	}
	file_gugumanager_extension_runner_v1_runner_proto_msgTypes[1].OneofWrappers = []any{
		(*Response_Hello)(nil),
		(*Response_Progress)(nil),
		(*Response_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gugumanager_extension_runner_v1_runner_proto_rawDesc), len(file_gugumanager_extension_runner_v1_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gugumanager_extension_runner_v1_runner_proto_goTypes,
		DependencyIndexes: file_gugumanager_extension_runner_v1_runner_proto_depIdxs,
		MessageInfos:      file_gugumanager_extension_runner_v1_runner_proto_msgTypes,
	}.Build()
	File_gugumanager_extension_runner_v1_runner_proto = out.File
	file_gugumanager_extension_runner_v1_runner_proto_goTypes = nil
	file_gugumanager_extension_runner_v1_runner_proto_depIdxs = nil
}
